name: Renovate
on:
  schedule:
    - cron: '0 23 * * *'
  workflow_dispatch:

jobs:
  renovate:
    runs-on: ubuntu-latest
    timeout-minutes: 5
    steps:
      - name: Get GITHUB_TOKEN for Github Apps
        uses: nabeken/go-github-apps@8eb7ca72b1a91f936373b9b0a072694aef88c981 # v0
        id: go-github-apps
        with:
          installation_id: ${{ secrets.renovate_app_inst_id }}
          app_id: ${{ secrets.renovate_app_id }}
          private_key: ${{ secrets.RENOVATE_APP_PRIV_KEY }}
          version: "0.1.7"

      - name: Checkout
        uses: actions/checkout@c85c95e3d7251135ab7dc9ce3241c5835cc595a9 # v3.5.3

      - name: Setup node
        uses: actions/setup-node@e33196f7422957bea03ed53f6fbb155025ffc7b8 # v3.7.0

      - name: Renovate
        uses: renovatebot/github-action@23a02fe7be9e93f857a953cc8162e57d2c8401ef # v39.0.1
        with:
          configurationFile: .github/renovate-global.json
          token: '${{ steps.go-github-apps.outputs.app_github_token }}'
        env:
          LOG_LEVEL: debug
